- name: Bring up inventory group of hosts
  docker_container:
    # TODO: |default(random_hostname)
    name: "{{ item }}"
    image: "{{ hostvars[item].image|default(provision_docker_image_default) }}"
    privileged: "{{ hostvars[item].privileged|default(provision_docker_privileged) | bool}}"
    state: "{{ hostvars[item].provision_docker_state | default(provision_docker_state) }}"
    restart: "{{ hostvars[item].restart|default(True) }}"
    tls: "{{ provision_docker_use_tls }}"
    stop_timeout: 1
    tty: "{{provision_docker_use_docker_connection | bool}}"
    exposed: "{{ hostvars[item].expose|default(['1-65535']) }}"
    ports: "{{ hostvars[item].ports|default(omit) }}"
    command: "{{ hostvars[item].command|default(omit) }}"
    env: "{{ hostvars[item].env|default(omit) }}"
    links: "{{ hostvars[item].links|default(omit) }}"
    network_mode: "{{ hostvars[item].network_mode|default(provision_docker_network) }}"
    volumes: "{{ provision_docker_volumes|default(omit) }}"
    volumes_from: "{{ provision_docker_volumes_from|default(omit) }}"
    pull: "{{ hostvars[item].pull|default(omit) }}"
  with_items: "{{ provision_docker_inventory_group }}"

- name: Get IP of container
  command:
    args: "docker inspect --format '{{ '{{' }} .NetworkSettings.IPAddress {{ '}}' }}' {{ item }}"
  register: provision_docker_ip
  delegate_to: localhost
  with_items: "{{ provision_docker_inventory_group }}"
  changed_when: false

- block:
    - name: "Associate ip address with hosts"
      set_fact:
        ansible_ssh_host: "{{ provision_docker_ip.results[item.0].stdout }}"
        ansible_ssh_user: "{{ hostvars[item.1]['ansible_ssh_user']|default(provision_docker_ssh_user) }}"
        ansible_ssh_pass: "{{ hostvars[item.1]['ansible_ssh_pass']|default(provision_docker_ssh_pass) }}"
      delegate_to: "{{ item.1 }}"
      delegate_facts: True
      with_indexed_items: "{{ provision_docker_inventory_group }}"
      changed_when: false
    - name: "Set ip address with /tmp/hosts"
      lineinfile:
        path: /tmp/hosts
        line: "{{ provision_docker_ip.results[item.0].stdout }} {{item.0}} {{item.1}}"
        state: present
      # delegate_to: "localhost"
      # delegate_facts: True
      with_indexed_items: "{{ provision_docker_inventory_group }}"
      changed_when: false

    - name: Wait for ssh
      wait_for:
        host: "{{ hostvars[item]['ansible_ssh_host'] }}"
        port: 22
        timeout: 60
        connect_timeout: 5
      with_items: "{{ provision_docker_inventory_group }}"
      when: not provision_docker_use_docker_connection

    - name: Make sure ssh is really up
      ping:
      delegate_to: "{{ item }}"
      with_items: "{{ provision_docker_inventory_group }}"
  when: not provision_docker_use_docker_connection

- block:
    # TODO: copy ALL host vars in the inventory
    - name: "Add docker hosts with connection docker"
      add_host:
        module: add_host
        name: "{{ item.1 }}"
        docker_ip: "{{ provision_docker_ip.results[item.0].stdout }}"
        ansible_connection: docker
        ansible_user: root
        groups: "{{ provision_docker_groups | union(item.1['groups']|default([])) | join(',') }}"
      with_indexed_items: "{{ provision_docker_inventory_group }}"
      changed_when: false
  when: provision_docker_use_docker_connection

